name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    # - name: Build with Maven
    #   run: mvn -B package --file pom.xml
    - name: Build with Maven
      run: mvn clean package

  build-and-push-to-docker-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

    #    - name: Log in to Docker Hub
    #     uses: docker/login-action@v2
    #     with:
    #       registry: docker.io # Optional, good practice to be explicit
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Log in to Docker Hub
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_USERNAME: ankush2642
          DOCKER_PASSWORD: dckr_pat_F08gPGVU40KpYSP4-77lSbPaX-8

      - name: Build the Docker image
        run:  docker build ./ -t ankush2642/java-maven:latest

      - name: Push the Docker image
        run: docker push ankush2642/java-maven:latest

  # publish-job:
  #   runs-on: ubuntu-latest
  #   needs: build_test
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: actions/setup-java@v3
  #     with:
  #       java-version: '17'
  #       distribution: 'temurin'
  #   - run: mvn --batch-mode --update-snapshots verify
  #   - run: mkdir staging && cp target/*.jar staging
  #   - uses: actions/upload-artifact@v3
  #     with:
  #       name: Package
  #       path: staging