# name: Java Maven Build & Publish to DockerHub

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build_test:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Set up JDK 17
#       uses: actions/setup-java@v3
#       with:
#         java-version: '17'
#         distribution: 'temurin'
#         cache: maven
#     - name: Build with Maven
#       run: mvn clean package

#   build-and-push-to-docker-hub:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           registry: docker.io # Optional, good practice to be explicit
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_PASSWORD }}

#       - name: Build the Docker image
#         run:  docker build ./ -t ${{ secrets.DOCKERHUB_USERNAME }}/java-maven-test2:latest

#       - name: Push the Docker image
#         run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/java-maven-test-2:latest

# Workflow name for clarity
name: Java Maven Build, Test & Publish to DockerHub

# Trigger on pushes and pull requests to the "main" branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Define the jobs to be executed
jobs:
  build_and_test:
    # Specify the runner environment
    runs-on: ubuntu-latest

    # List the steps in the job
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v3

      - name: Setup JDK 17  # Ensure Java 17 is available
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven' # Cache dependencies for faster builds

      - name: Build and Test
        run: mvn clean package -B  # Build in batch mode, consider 'mvn test' if tests exist

  build_and_push_to_docker_hub:
    # This job depends on the successful completion of build_and_test
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          registry: docker.io 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        run: |   # Multi-line command for better readability
          docker build \
            --file ./Dockerfile \  # Use an explicit path to your Dockerfile
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/java-maven-test2:latest \
            . 

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/java-maven-test2:latest
