name: Java Maven Build, Test & Publish to DockerHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v3

      - name: Setup JDK 17  # Ensure Java 17 is available
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven' # Cache dependencies for faster builds

      - name: Build and Test
        run: mvn clean package -B  # Build in batch mode, consider 'mvn test' if tests exist

  build_and_push_to_docker_hub:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          registry: docker.io 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        run:  docker build ./ -t ${{ secrets.DOCKERHUB_USERNAME }}/java-testing:latest

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/java-testing:latest
